### ISSUE TITLE
Should 'edges' be set to OptionType(ListType(...))?

### ISSUE THREAD

**Issue by jbohman** [sangria-graphql/sangria-relay#17]
See: https://github.com/sangria-graphql/sangria-relay/blob/cb608d04b63ab1f2cd8eae030d546e6fb68ef65c/src/main/scala/sangria/relay/Connection.scala#L57-L59

According to the relay specification this should return a list https://facebook.github.io/relay/graphql/connections.htm#sec-Edges and it seems like the javascript implemention does just that.

Any reason for adding the OptionType?

**Comment by OlegIlyenko** [comment]
Based on the spec, the introspection result looks like this for an `edges` field:

```json
{
  "name": "edges",
  "type": {
    "name": null,
    "kind": "LIST",
    "ofType": {
      "name": "ExampleEdge",
      "kind": "OBJECT"
    }
  }
}
```

Since all GraphQL types are nullable (or `Option`al)  by default, introspection results as well as reference implementation have just a `list` type. In sangria it is inverted, and you need to explicitly use `OptionType` to mark a type as optional, so this is where it comes from. (on the other hand, reference implementation defines a `GraphQLNotNull` type, to mark field a mandatory or non-null. In sangria you don't need to do anything special because everything is not-null by default).

**Comment by Malax** [comment]
I think this issue can be closed by now, right?
