### ISSUE TITLE
Support Scalajs

### ISSUE THREAD

**Issue by pasviegas** [sangria-graphql/sangria-relay#2]
Hey, are you planning  to support scalajs? 

Thanks

**Comment by OlegIlyenko** [comment]
At the moment I'm focusing more in the core functionality. So currently scalajs is not a priority, but as soon as library stars to take a good shape I may look into it. There is also a bit more info in the google groups about it: https://groups.google.com/forum/m/#!topic/sangria-graphql/oxiZwUXDG74

Just out of curiosity, what use-cases do you see for sangria scalajs support?

**Comment by pasviegas** [comment]
My main goal is to substitute a small single page app with scalajs. 

Right now it is a JS React code base and I think GraphQL/Relay would be of great help, so I was just assessing if that would be possible :)

**Comment by OlegIlyenko** [comment]
The thing is, main goal of sangria project is to provide a schema definition DSL and an GraphQL execution engine for the server side applications. I can imagine some scenarios where one can reuse some parts of it on the client side (like the query validator in combination with the schema materializor that may come in future). I can imagine some use-cases where these parts can be useful, but thy all more focused around tooling, rather than actual applications, that use for instance relay.

As far as I can tell, in your case you actually need a relay scalajs library. And it's out of scope of sangria project. Since relay framework establishes a data protocols between server and client (it defines some standard types like `Node`, `Connection`, `Edge`, etc) it can be helpful to provide these standard types in a library. That's the purpose of sangria-relay. But it's not a relay framework implementation itself. So I doubt that it will be helpful in your case, even if sangria and sangria-relay were published as scalajs libraries.

**Comment by OlegIlyenko** [comment]
closing this issue for now. If scalajs support would be added, then it will start in the main library and propagated here.
